### ISSUE TITLE
MELD and CUDA_VISIBLE_DEVICES under SLURM 

### ISSUE THREAD

**Issue by ca-taylor** [maccallumlab/meld#84] opened 2021-05-11 15:15 UTC
We are routinely hitting the error below...

  `File "/apps/cuda/11.0.207/gcc/9.3.0/openmpi/4.0.4/openmm/7.5.0/lib64/python3.8/site-packages/simtk/openmm/openmm.py", line 16117, in __init__
    this = _openmm.new_Context(*args)
simtk.openmm.OpenMMException: Illegal value for DeviceIndex: 6
`

We are a SLURM site using the cons/tres plugin so our GPUs are allocated by device and may not be allocated sequentially.  SLURM allocates GPUs on a given host and then sets CUDA_VISIBLE_DEVICES on that host.   MELD appears to parse the CUDA_VISIBLE_DEVICES string to build a list of devices (gpus) to hand to OpenMM.   So when SLURM assigns,

          CUDA_VISIBLE_DEVICES=0,1,2,3,4,6

the application should see 6 devices indexed 0..5, sequentially.   Instead, MELD appears to be passing the *physical* device indices to OpenMM.  Then, when OpenMM performs the following check,

`        if (deviceIndex < -1 || deviceIndex >= numDevices)
            throw OpenMMException("Illegal value for DeviceIndex: "+intToString(deviceIndex));`

It throws the exception because there are 6 devices allocated that Meld+OpenMM should see as devices 0..5.  Instead, MELD is passing them to OpenMM such that OpenMM sees a deviceIndex=6 which I think should not be happening.

Am I interpreting this correctly?   Has anyone else run into this issue.   

I suppose I could just comment out the numDevices check in OpenMM but that doesn't seem like the best approach to me.

**Comment by ca-taylor** [comment] 2021-05-11 16:04
The following patch (from a member of the Perez lab) appears to fix the problem.  Whether or not it is the _best_ way to fix the problem or not, I do not know.  

`--- comm.py.orig	2021-05-11 11:30:42.406440087 -0400
+++ comm.py	2021-05-11 11:33:44.044574712 -0400
@@ -335,10 +335,9 @@
             hostname = platform.node()
             try:
                 env_visible_devices = os.environ["CUDA_VISIBLE_DEVICES"]
+                env_visible_devices = [int(i) for i in range(len([int(dev) for dev in env_visible_devices.split(",")]))]
                 logger.info("%s found cuda devices: %s", hostname, env_visible_devices)
-                visible_devices: Optional[List[int]] = [
-                    int(dev) for dev in env_visible_devices.split(",")
-                ]
+                visible_devices: Optional[List[int]] = env_visible_devices
                 if not visible_devices:
                     raise RuntimeError("No cuda devices available")
             except KeyError:
`

**Comment by ccccclw** [comment] 2021-05-11 16:05
I ran into this issue previously and naively set
`env_visible_devices = [int(i) for i in range(len([int(dev) for dev in env_visible_devices.split(",")]))]`
in comm.py to avoid it.

**Comment by ca-taylor** [comment] 2021-05-11 16:11
> I wonder if this is a difference between your slurm configuration and the ones we typically run on?

It may be that we allocate individual GPUs as GRESs (generic resources) rather than allocating whole nodes (and any/all GPUs on them).  In our case a job will usually get a somewhat random subset of the GPUs on a node and SLURM delineates that subset via CUDA_VISIBLE_DEVICES.

**Comment by jlmaccal** [comment] 2021-05-11 16:23
The issue is what I mentioned above. I'm just not sure about the cleanest way to fix it.

We didn't run into this issue for two reasons:
1. MELD was originally developed on a cluster with 2 GPUs per node, where the current code is correct.
2. We always request "full nodes" when we run, so we don't have gaps in `CUDA_VISIBLE_DEVICES`.

I think the fix from @ccccclw is more or less the way we should handle it.

**Comment by jlmaccal** [comment] 2021-05-12 00:02
This should be fixed by the changes in the latest master branch.

**Closed** 2021-05-12 00:01 UTC

**Comment by ca-taylor** [comment] 2021-05-12 11:19
> This should be fixed by the changes in the latest master branch.

That is great.  Thank you.  Will there be a new "release" (0.4.20?) any time soon?

**Comment by jlmaccal** [comment] 2021-05-12 15:01
At this point, I think the next release will be 0.5.1. We have made a large number of improvements and bug fixes. I'm not sure on the exact timing though, as some of the changes rely on features in OpenMM that aren't yet released.

**Comment by jlmaccal** [comment] 2021-05-12 15:02
I could probably backport the changes in this fix to a 0.4.20 though.

**Comment by jlmaccal** [comment] 2021-05-12 16:11
I just tagged a new 0.4.20 release that has the changed negotiate_device_id logic.

**Comment by ca-taylor** [comment] 2021-05-12 16:27
> I just tagged a new 0.4.20 release that has the changed negotiate_device_id logic.

That is terrific.  Thank you!
