### ISSUE TITLE
Error report from setup.py

### ISSUE THREAD

**Issue by ajithperera** [maccallumlab/meld#155] opened 2023-10-06 21:50 UTC
Hello: I have been trying to build GitHub version (0.6.1) on RHEL8 with gcc/12.2.0 cuda/12.2.2,openmpi/4.1.5 python/3.11 openmm/8.0.0. I get the following error when I run "python setup.py build"

Traceback (most recent call last):
  File "/dist/apps/meld/meld/setup.py", line 2, in <module>
    from meld import __version__
  File "/dist/apps/meld/meld/meld/__init__.py", line 16, in <module>
    from meld.vault import DataStore
  File "/dist/apps/meld/meld/meld/vault.py", line 16, in <module>
    from meld.system import options
  File "/dist/apps/meld/meld/meld/system/options.py", line 15, in <module>
    @partial(dataclass, frozen=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/gcc/12.2.0/openmpi/4.1.5/python/3.11.5/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/apps/gcc/12.2.0/openmpi/4.1.5/python/3.11.5/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/gcc/12.2.0/openmpi/4.1.5/python/3.11.5/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/gcc/12.2.0/openmpi/4.1.5/python/3.11.5/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'openmm.unit.quantity.Quantity'> for field pressure is not allowed: use default_factory

As far as I can tell, this is something that can be fixed as MELD level.   I am a colleague of Alberto at UF and I hope someone can attend to this promptly. 

Best regards, Ajith

**Comment by jlmaccal** [comment] 2023-10-10 01:46
This is likely due to MELD not being updated for the latest version of python. If you downgrade, it should work until we have a chance to fix it.

**Comment by ajithperera** [comment] 2023-10-10 06:06
Thank you. Perhaps you can give me a hand on how to get around this SWIG
issue with
%factory. I have followed your discussion with openmm team (#3989).  The
openmm claims that
they fixed it ( Added missing include in SWIG header (#3999
<https://github.com/openmm/openmm/pull/3999>). I made sure that the fix
(in wrappers/python/src/swig_doxygen/swigInputBuilder.py
<https://github.com/openmm/openmm/commit/012188b8fca51ae08ee8430e542531e1b6e771f6#diff-752e0867c48dd7b939bb242f2978d453ed48fe0335009739c4cdd049547c10a0>)
is in our openmm/8.0.0 (we
have swig/4.1.1). However, this does not fix the problem I am having with
MELD plugin build.

Openmm suggestion to you was "This was broken by a SWIG update. To fix it,
you just need to
add %include "factory.i" to your interface file. See openmm/openmm-torch#96
<https://github.com/openmm/openmm-torch/pull/96>. Though we should
add the include to OpenMMSwigHeaders.i so downstream packages don't need
to." You respond with
 an affirmative. Which file in MELD did you change to get around this
(MeldPlugins.i?). Could you kindly
tell me which file should I modify?

Thanks, best regards, Ajith

**Comment by jlmaccal** [comment] 2023-10-11 14:03
These are two separate issues. Please open another issue for the second one.

For the first issue, the problem is that default pressure has an OpenMM unit attached. OpenMM units are mutable. In recent versions of python, DataClass does not allow a mutable default item. The fix is modify `RunOptions` so that pressure uses a field. That field should have `default_factory` set to a function that returns `1.0 * u.bar`.

Do you think it would be possible to try that fix from your end? And if it works, make a pull request?

**Comment by jlmaccal** [comment] 2023-10-18 23:12
This should be fixed by #157

**Closed by jlmaccal** 2023-10-18 23:12 UTC
